# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from kpTranslator.models.base_model_ import Model
from kpTranslator import util


class QNode(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, curie=None):  # noqa: E501
        """QNode - a model defined in OpenAPI

        :param curie: The curie of this QNode.  # noqa: E501
        :type curie: str
        """
        self.openapi_types = {
            'curie': str
        }

        self.attribute_map = {
            'curie': 'curie'
        }

        self._curie = curie

    @classmethod
    def from_dict(cls, dikt) -> 'QNode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QNode of this QNode.  # noqa: E501
        :rtype: QNode
        """
        return util.deserialize_model(dikt, cls)

    @property
    def curie(self):
        """Gets the curie of this QNode.

        CURIE identifier for this node  # noqa: E501

        :return: The curie of this QNode.
        :rtype: str
        """
        return self._curie

    @curie.setter
    def curie(self, curie):
        """Sets the curie of this QNode.

        CURIE identifier for this node  # noqa: E501

        :param curie: The curie of this QNode.
        :type curie: str
        """

        self._curie = curie
